### ISSUE TITLE
Gracefully handle database locks

### ISSUE THREAD

**Issue by adityahase** [frappe/agent#93]
```python
09:02:01 [Job e1dbd1e6-1e48-4d19-a8e5-26bb50102e2b]: exception raised while executing (backup_job)
Traceback (most recent call last):
  File "/home/frappe/agent/env/lib/python3.8/site-packages/peewee.py", line 3057, in execute_sql
    cursor.execute(sql, params or ())
sqlite3.OperationalError: database is locked

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/frappe/agent/env/lib/python3.8/site-packages/rq/worker.py", line 1359, in perform_job
    rv = job.perform()
  File "/home/frappe/agent/env/lib/python3.8/site-packages/rq/job.py", line 1178, in perform
    self._result = self._execute()
  File "/home/frappe/agent/env/lib/python3.8/site-packages/rq/job.py", line 1215, in _execute
    result = self.func(*self.args, **self.kwargs)
  File "/home/frappe/agent/repo/agent/job.py", line 133, in wrapper
    raise e
  File "/home/frappe/agent/repo/agent/job.py", line 125, in wrapper
    result = wrapped(*args, **kwargs)
  File "/home/frappe/agent/repo/agent/site.py", line 654, in backup_job
    backup_files = self.backup(with_files)
  File "/home/frappe/agent/repo/agent/job.py", line 109, in wrapper
    instance.step_record.success(result)
  File "/home/frappe/agent/repo/agent/job.py", line 44, in success
    self.end()
  File "/home/frappe/agent/repo/agent/job.py", line 37, in save
    instance.model.save()
  File "/home/frappe/agent/env/lib/python3.8/site-packages/peewee.py", line 6431, in save
    rows = self.update(**field_dict).where(self._pk_expr()).execute()
  File "/home/frappe/agent/env/lib/python3.8/site-packages/peewee.py", line 1845, in inner
    return method(self, database, *args, **kwargs)
  File "/home/frappe/agent/env/lib/python3.8/site-packages/peewee.py", line 1916, in execute
    return self._execute(database)
  File "/home/frappe/agent/env/lib/python3.8/site-packages/peewee.py", line 2400, in _execute
    cursor = database.execute(self)
  File "/home/frappe/agent/env/lib/python3.8/site-packages/peewee.py", line 3070, in execute
    return self.execute_sql(sql, params, commit=commit)
  File "/home/frappe/agent/env/lib/python3.8/site-packages/peewee.py", line 3064, in execute_sql
    self.commit()
  File "/home/frappe/agent/env/lib/python3.8/site-packages/peewee.py", line 2831, in __exit__
    reraise(new_type, new_type(exc_value, *exc_args), traceback)
  File "/home/frappe/agent/env/lib/python3.8/site-packages/peewee.py", line 183, in reraise
    raise value.with_traceback(tb)
  File "/home/frappe/agent/env/lib/python3.8/site-packages/peewee.py", line 3057, in execute_sql
    cursor.execute(sql, params or ())
peewee.OperationalError: database is locked
```

**Comment by adityahase** [comment]
Handled with https://github.com/frappe/agent/pull/95
